### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#1]
I took a screenshot of all the different graph axis labels/titles and made them the same size next to each other. I think the labels are all one font and the titles are perhaps a different font or just bolded (but consistent fonts within titles). It does appear that the 'Amplitude' on the oscillogram at the bottom gets cut off a bit. Should I make all the labels and titles the same size? Or should the titles be the same as the axis labels? Or both? 

[
<img width="640" alt="Screen Shot 2019-06-25 at 8 41 07 PM" src="https://user-images.githubusercontent.com/35315239/60150338-1fba5980-978d-11e9-8f23-88b7673fe0b9.png">
](url)

**Comment by hglanz** [comment]
Let's try one size for the titles and one (different) size for the axis labels...? But the same font and boldness for all.....and see how this looks.

**Comment by hglanz** [comment]
In future github issues, please tag me using @hglanz so that I get an email notification. Thanks! :) @michalg04

**Comment by michalg04** [comment]
Here is the before and after with font size changes! Does that look good? @hglanz 
<img width="690" alt="Screen Shot 2019-07-02 at 10 35 01 AM" src="https://user-images.githubusercontent.com/35315239/60534134-ff6f2b00-9cb5-11e9-805e-4ba45ad1061f.png">
<img width="712" alt="Screen Shot 2019-07-02 at 10 38 43 AM" src="https://user-images.githubusercontent.com/35315239/60534147-0433df00-9cb6-11e9-8d31-5d6d8e508050.png">

**Comment by michalg04** [comment]
The first picture is missing 'Amplitude (dB)' just because I took two screenshots and put them together and that label got accidentally cut out. The bottom one is what it looks like now!

**Comment by hglanz** [comment]
@michalg04 yes! This looks great. Nice work.
