### ISSUE TITLE
Question about the 2 red lines on graphs

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#10]
I made the two red lines thicker/bolder on the oscillogram and also added them to the spectrogram, but I saw that to-do item within the spectrum. Should there be two red lines on the spectrum as well? 
@hglanz @mschrothglanz

**Comment by mschrothcp** [comment]
@michalg04 No, there shouldn't be red lines in the spectrum. Rather, the dotted black lines in the spectrogram should show up on the spectrum as well. Thanks for that fix!
