### ISSUE TITLE
To-Do Items from/for Glanz

### ISSUE THREAD

**Issue by hglanz** [hglanz/AcousticsApp-Summer2019#11]
- Methods for custom error messages
- How is minimum for spectrum determined?
- Descriptive stats for segments
- Information for "About" tab
- Information about Cal Poly server resources

**Comment by hglanz** [comment]
@michalg04 

As far as Cal Poly server resources, check out 

https://github.com/ellisonbg/dirac-cluster/wiki

This should be a better place to run things, but you'll still need a display for the app....unless you can figure that out too using dirac. If not, try reaching out to Colby Bell in our college for assistance and please CC me; just mention what you're working on and what you'd like to do.

cbell18@calpoly.edu

**Comment by michalg04** [comment]
@hglanz now that I am using a different segmentation method, everything runs a lot faster than during our last meeting. Is it okay if I continue to run the app of my server and not Cal Poly's?
