### ISSUE TITLE
Legend for 7th graph in windows function help

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#13]
@hglanz @mschrothglanz I think I need a bit more detail on how to create the legend for the 7th graph in windows function help. The function used to created it doesn't come with any auto made legends like the spectrogram, and I couldn't find anything online to help me understand the meaning of the colors in that graph. Do you guys have any insight into how the colors are determined?

**Comment by michalg04** [comment]
I'm still not sure how to match each curve to a color since there are 6 curves but I can only see 4 colors (red, light blue, dark blue, and pink) @hglanz @mschrothglanz

**Comment by hglanz** [comment]
@michalg04 I'm pretty sure the spectrum function is plotting the 6 curves using the first 6 colors: black, red, green, blue, cyan, magenta (in this order). This is just an educated guess though. You could just plot the parts of the spectrum that seem to show the most differentiation to check...

In any case, if my guess is correct then I believe it should be

rectangle - black
bartlett - red
hamming - green
hanning - blue
blackman - cyan
flattop - magenta

**Comment by michalg04** [comment]
Got it, thank you! Is it okay that we aren't seeing green and black really @hglanz?  
<img width="837" alt="Screen Shot 2019-08-13 at 3 55 29 PM" src="https://user-images.githubusercontent.com/35315239/62983082-04f67f80-bde3-11e9-9962-4a7d43d25be0.png">

**Comment by hglanz** [comment]
Let's say it's ok for now and we'll consult @mschrothglanz when she returns.
