### ISSUE TITLE
interactive graphs update

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#15]
@hglanz @mschrothglanz 
I've been working on getting the interactive graphs to look more like the static ones but I'm not sure if I'm going to be able to get it to look identical or very close.
<img width="618" alt="Screen Shot 2019-10-27 at 7 02 52 PM" src="https://user-images.githubusercontent.com/35315239/67646737-bbe79f00-f8ec-11e9-8da3-2c6d3a292ebd.png">
<img width="131" alt="Screen Shot 2019-10-27 at 7 08 28 PM" src="https://user-images.githubusercontent.com/35315239/67646844-24368080-f8ed-11e9-9e61-b8005254c790.png">
The sine option looks the worst for both the spectrogram and the spectrum. When I save spectrum values, there is no difference between the values that we see in the red (correct) graph and the black interactive graphs. What makes the red graph look different from the black graph is when I set frequency limits. What's weird is that the frequency limits don't change the values in the data frame, but they do make the graph have that middle dip. I have a suspicion that the frequency values are actually mirrored across the x-axis somehow. @mschrothglanz is that a possibility?
However, the dolphin and whale files are looking better!
<img width="613" alt="Screen Shot 2019-10-27 at 7 03 46 PM" src="https://user-images.githubusercontent.com/35315239/67646738-bdb16280-f8ec-11e9-911b-1224fd102f74.png">
Let me know if I should continue down this path.

**Comment by mschrothcp** [comment]
@michalg04 
I'm so happy to hear that the mammal graphs are starting to look better. I have a sneaking suspicion that the black spectrum is being aliased and picking up the lowest frequency present rather than the  actual frequency of the sine wave. You may try changing the sampling frequency and see if this issue keeps arising. Let me know what happens.

**Comment by michalg04** [comment]
@mschrothglanz I tried changing the sampling frequency and it doesn't change the way the graph looks. It also displays the correct sampling frequency. The only thing that changes the red graph to look right and differ from the black graph is the frequency range, but unfortunately that doesn't change the data frame that the function returns so the black graph doesn't change. The black graph has a long horizontal stretch that almost reaches 0 amplitude and so does the red graph, but for the red graph the long stretch is in the middle which is what made me think that it's being mirrored. The minimum frequency is 0 which is where the black graph is stopping. Not sure how the red graph was created.

**Comment by mschrothcp** [comment]
@michalg04 @hglanz hmmm it seems like this might have to be something I view in person (especially since my acoustics brain is currently being stored in the closet). Since the other files seem to work appropriately, I would say to keep moving down this same path. Does that seem good @hglanz?

**Comment by hglanz** [comment]
@michalg04 go ahead and continue....and perhaps let's try to set up a meeting to look over these things in person. @mschrothglanz 
Could we plan on some day/time next week?

**Comment by michalg04** [comment]
@hglanz @mschrothglanz works for me! I think a meeting would be helpful.
On the bright side - I just got the oscillogram to look good.

**Comment by mschrothcp** [comment]
@hglanz @michalg04 Would next Friday work? I know Wednesday's are crazy for @hglanz and  Tuesdays/Thursdays are hard for me. Is Friday too late?

**Comment by hglanz** [comment]
@michalg04 @mschrothglanz Next Friday works for me, but it has to be 7-8, 10-11, 11-12, or after 4. Sorry. Or you two could meet without me potentially.

**Comment by michalg04** [comment]
@hglanz @mschrothglanz I can do any of those times except for 10-11. Let me know which time you guys would prefer!

**Comment by mschrothcp** [comment]
@michalg04 @hglanz 11-12 on Friday 11/14 it is!
