### ISSUE TITLE
Interactive Graphs Update

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#16]
@hglanz @mschrothglanz I just wanted to update you both that I got the three graphs to share axis and interact together (I know Dr. Glanz made a note to look into it). I'm going to work on making it look nicer with their size, font, and the dot size on the spectrogram. I'll send picture updates once it looks nice!

**Comment by mschrothcp** [comment]
@michalg04 That is awesome news!! I can't wait to see it! You're doing great work for us!

**Comment by hglanz** [comment]
Ditto what @mschrothglanz said! :D

**Comment by michalg04** [comment]
@hglanz @mschrothglanz here's a visual update:
<img width="636" alt="Screen Shot 2019-11-18 at 7 15 08 PM" src="https://user-images.githubusercontent.com/35315239/69113345-9c4d1d80-0a37-11ea-977c-b192df60266a.png">
<img width="659" alt="Screen Shot 2019-11-18 at 7 15 56 PM" src="https://user-images.githubusercontent.com/35315239/69113348-9d7e4a80-0a37-11ea-8411-a688e2e9f7bb.png">
<img width="646" alt="Screen Shot 2019-11-18 at 7 10 25 PM" src="https://user-images.githubusercontent.com/35315239/69113352-9fe0a480-0a37-11ea-81c6-e5156c8e6d79.png">

I haven't worked on the dot size yet but that's my next task. If there is something you think I should work on before that let me know! Thank you!

**Comment by mschrothcp** [comment]
@michalg04 these look great! One question, the oscillogram for the Dolphin file doesn't look like I would expect it to. Did something happen?

**Comment by michalg04** [comment]
@mschrothglanz fixed it! The oscillogram was not updating the correct time window. Now it looks the same as what we've seen before.

**Comment by mschrothcp** [comment]
This is so exciting! @michalg04 would you be willing to "push it" so that I can play around with it?

**Comment by michalg04** [comment]
@mschrothglanz republished!

**Comment by mschrothcp** [comment]
@michalg04 I look forward to perusing through it over the next couple of weeks. As I see some issues I will post about them.

Thanks so much! It's looking great! Have a great week!
