### ISSUE TITLE
Upcoming Meeting 

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#17]
@hglanz and I were talking about having another meeting potentially next week. I'm done with finals on Wednesday. When is the best time/day for you both @mschrothglanz?

**Comment by mschrothcp** [comment]
@michalg04 Would Friday the 13th work? You may already have left town by then, but I thought I would just check.

**Comment by michalg04** [comment]
@mschrothglanz I'm planning on leaving Thursday evening! I also may have spoken too fast, I moved a final to Thursday 10-1pm. So maybe Thursday at 1:10pm? Or is that too late?
