### ISSUE TITLE
Recent Updates

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#18]
Hi all! Hope you had a great winter break. I wanted to update you guys on the recent app updates and I also republished it so you can see it. Mainly, I changed the main page to only interactive graphs. Otherwise, I've fixed minor problems such as numbers facing up on the graphs, getting rid of hover values on the graphs, and added horizontal grid lines and vertical red lines. I also added interactive zoom so you can see more tick lines when zooming in. 
If you recall during our last meeting we got rid of the "geom_tile" part of the spectrogram (this was creating unnecessary boxes behind the whale graph). However, turns out that those are necessary to graph the sine ones since for some reason the new spectrogram function can't locate those red/yellow high amplitude values but the tiles can. This is probably why all the examples I found online included the tiles. I haven't found a solution yet but let me know if you guys have ideas on it or want to meet to look over it! 
In the mean time, I'll be working on getting the graphs to align better with the vertical red lines (there's a weird gap in the whale graph), researching how to fix the spectrogram without tiles, and ways to make the app run faster. 
Thanks @hglanz @mschrothglanz!

**Comment by hglanz** [comment]
Sounds great @michalg04 ! Thanks for the updates. Interesting about the tiles for the sine ones....I'm not sure how to investigate this, but it seems worth exploring because I feel like we should only use the tiles or not use them at all....the other files just didn't look great with them both.

**Comment by michalg04** [comment]
@hglanz I've been working on understanding why the sine functions won't show up just with stat_contour and only with tiles and I think it is simply because the sine files don't really have shapes to contour over since its just continuous rectangular segments which is why nothing shows up without the tiles. Without the contour part, the graphs look pretty similar to what we had earlier this year. The whale especially is very pixilated, but the dolphin looks nicer. 
<img width="781" alt="Screen Shot 2020-01-13 at 11 34 52 AM" src="https://user-images.githubusercontent.com/35315239/72286035-2dd0aa00-35f9-11ea-9d07-f834c56252df.png">
<img width="715" alt="Screen Shot 2020-01-13 at 11 34 16 AM" src="https://user-images.githubusercontent.com/35315239/72286044-30cb9a80-35f9-11ea-8680-f468fc448d33.png">
I'm a bit conflicted since I think the whale, with both contour and tiles, even though it's not as ideal as without the tiles still looks better than the pixilated one above. On the other hand, having both tiles and contour will make the app even slower.

**Comment by hglanz** [comment]
@michalg04 great report! How big is the difference in speed when doing just contour or just tiles?

@mschrothglanz can you confirm what she's said about the contours of the sine files? What do you think about how they look?

**Comment by michalg04** [comment]
@hglanz it's not a huge difference, around a second or two faster on my computer.

**Comment by mschrothcp** [comment]
Hi @michalg04 and @hglanz! So, first, I'm terribly sorry for this VERY VERY delayed response!! Second, I've been looking at the app and have some things that I would like to chat about. 

Since the sine, triangular, and square wav files are all mechanically produced (not produced via nature) I think Michal might be correct about the fluidity of these wave files. I am less concerned with how those files are viewed than I am with the "nature" produced wav files. What is being plotted there now seems fine to me for the mechanical wav files.

@michalg04  you've done a fantastic job at getting the three graphs to match each other! I love that I can see the frequency values consistently across the spectrogram as well as the spectrum and when I zoom in they rescale. It's awesome!! This might be something I need to think about more, but I'm wondering if when we zoom in the spectrogram can become less pixelated....this may mean that the fft would have to be applied to the new "zoomed in time frame" in order to make the picture smoother, I'm just not sure.

Here are a couple of small adjustments to make:
1) Can we put a title on the spectrogram?
2) Is it possible to make it so the spectrogram only reaches -30dB (like our color range bar)?
3) One of the biggest issues is still time. It took around 5 minutes for my computer to show anything the first time I opened the app and every time I change a setting, the amount of time that elapses is too long. Also, it has frequently stopped working and required a reload. So, perhaps we can talk to Cal Poly people about this....just spit balling
4) While our pre-loaded files seem good, we still have issues with wav files that need to be uploaded. I grabbed a beluga recording and tried to use it, but this is what I saw:

![pic](https://user-images.githubusercontent.com/52642916/72642127-84ebbd00-3920-11ea-8216-96bc72de39f4.png)

I'm not sure what the solution is, but perhaps you guys might know.

Otherwise, I'M LOVING IT!

**Comment by hglanz** [comment]
@mschrothglanz Great comments!

1. What kind of title are you thinking? Could you be more specific?
3. @michalg04 Could you comment on how long the app takes locally on your own machine versus on shinyapps?
4. @mschrothglanz Have you loaded the beluga file into Raven to know what it should look like? It's hard to know what's wrong or what the issues are in your picture....I don't know very much about acoustics :P

**Comment by mschrothcp** [comment]
1) The title should just be Spectrum. I said spectrogram above, but I meant spectrum, sorry, my bad ;) The same thing goes for my second comment. Let's make it so the amplitude on the spectrum goes to -30dB
3) Here is what it should look like from raven
The top is the oscillogram and the bottom is the spectrogram
![image](https://user-images.githubusercontent.com/52642916/72763814-59740700-3b9a-11ea-880c-58807d5daf81.png)

**Comment by michalg04** [comment]
@mschrothglanz I can work on adding a title for the spectrum! It's a little more complicated now since the 3 graphs are intertwined and R thinks of them as one graphs, so only allows for one title. I'll try to find something to bypass it. 
I am not sure what you mean by "Let's make it so the amplitude on the spectrum goes to -30dB"? Do you mean on the spectrogram? In the spectrogram we are already setting the amplitude limits to not exceed -30db, as we do in the color scale. Meaning there is a line of code that tells the color scale to go from -30db to 0db and also a line of code that tells the spectrogram not to graph any values outside of (-30,0). Is there an indication this is not working? 
Could you also email me the beluga file so I can investigate it further? 
@hglanz I haven't been able to time the difference mainly because running it from shinyapps crashes almost every time. In general my computer has been running very slowly lately so it might not be an accurate indication of shinyapp website since @mschrothglanz has been able to at least get plots to load eventually. For sine files my computers runs about 5 seconds faster than shinyapp.

**Comment by mschrothcp** [comment]
For the spectrum, the axis (starting from right to left) goes from 0dB down to -100dB (depending on the file used). That's a bit extreme. It only needs to reach down to -30dB. Let's put that same line of code (to make it go from -30dB to 0dB) into the spectrum code. 

Here is the link to the beluga file: https://cis.whoi.edu/science/B/whalesounds/WhaleSounds/62019007.wav

You can try any of those sounds on the Watkins Marine Mammal Sound Database
https://cis.whoi.edu/science/B/whalesounds/index.cfm

**Comment by mschrothcp** [comment]
By the way, @michalg04, how can we convince you not to graduate and remain our research student for this next summer?! If you need me to I can sabotage any grades for you....I know people on the inside ;)

**Comment by michalg04** [comment]
@mschrothglanz I will work on the title and the spectrum amplitude change this weekend! I think the other files might need  a bit more time investigating because I was having a hard time understanding the problem upon initial research. 
I am actually technically graduating in the summer and not in the spring since I'll have 2 GEs left to complete. I would be open to doing Frost research with you guys again if that's an option! Not sure exactly where I'd be physically yet but I think convincing me to work on it over the summer won't require any grade sabotage (as of now!) although I appreciate the thought :)

**Comment by michalg04** [comment]
@mschrothglanz I changed the spectrum amplitude limits to (-30,0) and they are looking a bit off but I am not sure if that's what you were looking for. I also added the spectrum title. 
<img width="641" alt="Screen Shot 2020-01-23 at 2 49 50 PM" src="https://user-images.githubusercontent.com/35315239/73143703-435ebe80-4052-11ea-8102-e0227dbc8a87.png">
In terms of the Beluga file, I'm not able to figure out what exactly is not working there. Other files that I upload work correctly but I'll continue to research that.

**Comment by mschrothcp** [comment]
@hglanz Let's snag @michalg04 for the summer if we can! 

@michalg04 The image that you sent looks great. I have to say that I can't seem to load the app as it is taking an incredibly long time. So, I can't check other wav files myself to see if the beluga file was just a fluke (ha get it?!?! nerd jokes). 

It seems like we have gotten to a good point in the app....should we get together again to discuss steps moving forward? Or is this something we should just email about? What do you guys think?

**Comment by michalg04** [comment]
@mschrothglanz I think I actually fixed the beluga file but the joke still works! The one weird thing that still happens is that the dB color scale disappears when the graph is calculated. It doesn't happen in other files I upload so I'm still working on that. When I run it on my computer and open in a web browser it's actually pretty fast so maybe a meeting would be a good idea so I could show you guys in person.

**Comment by hglanz** [comment]
@michalg04 could you remind us of your schedule/availability this quarter?

**Comment by michalg04** [comment]
@hglanz @mschrothglanz my class schedule is as follow: 
Monday/Friday: 9-10am 
Tuesday/Thursday: 8-11am, 1:40-4:30pm
Wednesday: 9-11:30am
Exceptions: Monday Feb 3rd I have a doctors appointment at 2pm and Friday Feb 14th I'm going out of town. Otherwise I'm free :)

**Comment by hglanz** [comment]
@michalg04 @mschrothglanz how about Monday Feb. 3 at 11am?

**Comment by michalg04** [comment]
@hglanz works for me!

**Comment by mschrothcp** [comment]
@michalg04 and @hglanz it works for me as well. I have sent everyone an invitation. I'll see you on Monday!
