### ISSUE TITLE
Uploading to the Cal Poly Server

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#20]
Hi all!
I was working on uploading to the server and it seems that there's an issue with one of the packages we are using for fourier transforms. I am not sure if @hglanz you can see this log when you go to the server but I will attach the error message: 

"Error code: r-missing-system-library. An R package cannot be installed because a required system-level dependency is missing.
Possible causes:
An R package requires a system-level dependency, such as a library or executable, which is not installed on the Connect server.
Possible solutions:
Install the required package using your system package manager (such as apt or yum).
If you have RStudio Package Manager, open the information page for the affected R package. Installation instructions for the package's system-level dependencies are included under the Install System Prerequisites heading
Otherwise, use the messages in the deployment log to identify which system package you need to install."

From the logs I can see that the package/packages missing is "fftw" or "fftw3". I tried to solve the problem on my end, but from some googling I see that it looks like it's a package that needs to be on the server. I will do some more digging over the weekend, but if Dr. Bodwin or Dr. Glanz know how to fix this it might be faster. 

Thank you!

**Comment by michalg04** [comment]
Hi @hglanz @mschrothglanz! I did more research over the weekend and it looks like that error is related to the package missing on the server. Did you get a chance to check with Dr. Bodwin? Thank you!

**Comment by hglanz** [comment]
I'm so sorry @michalg04 , I didn't get a chance to check with Dr. Bodwin yet. I will today!

**Comment by michalg04** [comment]
@hglanz no problem, just wanted to check in!

**Comment by hglanz** [comment]
@michalg04 Dr. Bodwin is saying the fftw package is working fine for her. She's wondering if you can send her a screenshot of the error?

**Comment by michalg04** [comment]
@hglanz my computer is currently at the apple store (pray for me) so I don't have a good screenshot of the error at the moment, but I believe that either you or Dr. Bodwin can look at the logs for the acoustic app that we created last time and it should be there although I could be wrong. I was able to upload the app to our usual shinyapp server no problem, so it's just giving us trouble on the Cal Poly server. I should get my laptop back tonight so I will send screenshots if you guys can't see the logs!

**Comment by hglanz** [comment]
Dr. Bodwin is not seeing the app on the Cal Poly server....?

**Comment by hglanz** [comment]
Nevermind....maybe

**Comment by hglanz** [comment]
@michalg04 we've recently updated the server to R 4.0. Could you re-upload the app and try everything again as soon as you can and let us know the results?

**Comment by michalg04** [comment]
@hglanz I will do that tonight, thanks!

**Comment by michalg04** [comment]
@hglanz I tried uploading to the server again and that failed, then I upgraded my rstudio as well and I got the same error again (attached). Since I got the newer Rstudio, all the packages I had to re-download showed up as errors in the start which were easy to fix. This one shows up towards the end of the deployment perhaps indicating that it's more than just installing a package on my end? Not an expert but that is what the internet seems to think. Hopefully we can get this figured out! I'm still looking for solutions on my end. 
<img width="1135" alt="Screen Shot 2020-06-24 at 10 54 13 PM" src="https://user-images.githubusercontent.com/35315239/85664018-9de66000-b66e-11ea-9d3b-1e0d642cdef5.png">
[rstudio-connect.138.0.306.packrat_restore.N7RdtLxkojZDZe0s.log](https://github.com/hglanz/AcousticsApp-Summer2019/files/4829318/rstudio-connect.138.0.306.packrat_restore.N7RdtLxkojZDZe0s.log)

**Comment by michalg04** [comment]
@hglanz @mschrothglanz I got it up on the server! I tried removing the new additions with wavesurfer and it worked. It does load much faster although there's still lag especially with the dolphin file. There are a few bugs I noticed right away (like one of the red lines on the spectrogram disappeared) that I will get start on this weekend. Let me know what you guys think!

**Comment by mschrothcp** [comment]
Hi @michalg04, I'm sorry that it has taken me 11 days to respond to you. Who knows where those days have gone, it has been crazy. Regardless, that is no excuse and I'm sorry. 

I'm happy to hear that things are up and running. I have taken a look at the app and have a few observations. So, it seems that it is definitely faster than before (since before it never even loaded in time) which is a good thing. However, it still seems a bit slow and I need to click on "Reset Inputs" in order to make it fully load. Perhaps that is something we can investigate. I definitely would like to update my collaborator in SD, but would like some things fixed a bit before I do.
1 - We should try to figure out how to make the graphs (that we want) talk to each other so we don't have 2 oscillograms
2 - Fix the few bugs that we have discussed seeing.

What do you guys, @hglanz and @michalg04, think?

**Comment by michalg04** [comment]
@mschrothglanz did you see the double oscillograms on the Cal Poly cloud? The wavesurfer is what was preventing it from uploading so I removed it, meaning there should only be one there.

**Comment by mschrothcp** [comment]
@michalg04 Oh, interesting I just went to our original link. Can you post the new link on the github?

**Comment by michalg04** [comment]
@mschrothglanz https://rstudio.csm.calpoly.edu/content/147 here it is!
I believe @hglanz can change it to be something better than just a URL. 
In case you need to log in:
User: Marine_Acoustics 
Password: acousticapp

**Comment by mschrothcp** [comment]
@michalg04 Thank you! So I have perused it and it seems like loading might still take a bit of time. Is there something we can do about that (especially with the dolphin file). Also, it seems that some of the bugs that we mentioned in previous chats still exist (missing spectrum bar, pixilation of whale file, etc). If we can fix these issues I can send it off to my collaborator and see what she thinks. Of course she is still interested in the interactive playback button. Let me know your thoughts @hglanz and @michalg04

**Comment by michalg04** [comment]
@mschrothglanz I think that uploading it to the server was supposed to fix it taking so long. Maybe @hglanz and Dr. Bodwin can come up with something else but I'm not sure. Can you give me more details about the missing spectrum bar and pixilation of whale file? I think that pixilation is just a result of making those graphs ourselves and not using the package, I think that ever since we made it interactive it has looked like that. We did have a different version where it looked more like the original one, but I think it was inaccurate so we kept this one. @hglanz might remember better?  
Some of the pixilation dilemma is in Recent Updates #18.
