### ISSUE TITLE
Official to do for the App

### ISSUE THREAD

**Issue by mschrothcp** [hglanz/AcousticsApp-Summer2019#21]
Hi @michalg04! First, please allow me to DEEPLY apologize for the beyond delay in this response. I really can't tell you how sorry I am that we haven't been on top of this more for you, but I'm hoping that your job is distracting you from this fact ;). We are trying to move and there have been some crazy complications that we didn't prepare for. However, there really is no excuse!

Secondly, I do agree that the use of the server has drastically changed the speed. So I think for now, it looks good enough to send to my collaborator with respect to that. Thus, the only thing that I would like to work on before sending it off are the small fixes (listed below). Once we work on those, I will send it off, and we can start to think about the big issues and how to address them. Does that work for you guys @hglanz and @michalg04?

Small Fixes needed to send it off:
1 - The spectrum red dotted line disappears for the animal files but is there for the other wav files
2 - You need to put your name somewhere as an author. It's about time you make it yours. You can list yourself, then me, and then Hunter.
3 - We also want the About page as the front page.
4 - I believe we fixed the issues with the spectrum rates (can you confirm this?). I went through and tried them and it seems like they work. Can you tell me how we are calculating those values that are the options?
    4a - It seems like the sampling rate option slows down the app significantly (as with the dolphin file at least). Is there anything we can do to help mitigate that? This could be true for all of the side options...the overlapping seems to take a while as well.
5 - On the segmentation's tab, can we fix the Segmentation Help button. It doesn't seem to do anything. In it can we include a description of the Min Length of segments option  and Amplitude Threshold? I think those could be flushed out just a little more.

Big Changes:
1 - Of course, as we have discussed, the playback button (I think @hglanz may have some more ideas?.....)
2 - We have discussed this and I believe we came up with a solution (not sure though). Can we make the whale file seem less pixelated?
3 - Ability to load longer wav files.

Otherwise I think this looks beautiful! I'm so excited to send it to my collaborator in SD!
One more thing. The Frost coordinators would like us to submit pictures of your work. Specifically this is what I was told: "Yup, we'll take it, especially a Zoom screenshot of a group meeting, even if it's only the two of you. This year we could also use the pretty graphs that show the frequencies of the whale songs, or a still of her at home with those graphs on the computer screen. The whole remote thing makes the scene different this year." So we should schedule a time this week if we can to just chat about things and take a couple of pictures. If that works for you.

You are doing wonderful work @michalg04 . I am super pleased!

**Comment by michalg04** [comment]
Hi @mschrothglanz ! No problem at all. I am so excited for you guys and your new house!! Big congratulations on that. 
I started on some fixes. First I brought back the red dotted lines for all files. I think this problem started because I didn't like the gap between the red lines and the actual plot so I tried to fix the gap, which only worked for the non-marine animals. If the gap doesn't bother you that much, I think this will be okay for the time being. 
Second, I made the About page at the front and added our names at the bottom. Let me know if there are any typos or anything else I should add to it. 
Third, I checked on the segmentation help button. It does pop up a description at the bottom. Let me know if you see it or if you accidentally missed it last time. 
Regarding the sampling rate, from what I see every wave file has a built in sample rate which is what we grab unless the user specifies something else. I don't think I ever changed that so that might need some work but I'm not sure what exactly is wrong with it. 
Last wanted to check if you had a change to read through this discussion: https://github.com/hglanz/AcousticsApp-Summer2019/issues/18. This should explain why the whale is pixilated, and I don't think I have been able to fix it since it there is a function that smoothes it but it doesn't work for sine one. 
Thank you!

**Comment by mschrothcp** [comment]
Hi @michalg04 . Okay, so it is great to hear that in the small fixes you have knocked off tasks 1,2, and 3!

With respect to task 4 - Sampling Rate - You are correct that we grab the original sample rate from the file. However, we do give the user the option to change the sample rate. We have created a set of values that the user can choose. Can you remind me how we obtained those values? We should list that somewhere so that the user understands where they came from. I'm also a little concerned about the extra time that it is taking when we want to choose to change the sample rate, or the zero padding, etc. Can you tell me .. is this something we cannot speed up at this point in time? Are we at our fastest speed with the server?

With respect to task 5 - Segmentation Tab - You are correct that I must have missed it the first time. Can we make it a hover button (like we did on the exploration tab? Also, can you put a question mark help next to "Min Length of Segments (ms)"? If we can explain what changing those does briefly that would help also. You can do that in each of the individual question mark helps.

With respect to the Big Changes: task 2 - Pixelation - I remember going through that discussion. I remember that we chose to go in one direction to cover all the files because of time taken to produce. I'm wondering, if with the server now, we could use the contour with the whale and the rectangles for the others. In other words, can we pick the best method of presentation specific to each file? I'm hoping, that for the nature files, we can get back to something that looks like this:
![image](https://user-images.githubusercontent.com/52642916/88599053-a7713800-d01f-11ea-8970-5dad4cc0b3c5.png)

Let me know what you think. It may be a few days before I can respond again, as we start moving tomorrow. But I will for sure get back to you before the end of the weekend.

**Comment by michalg04** [comment]
Hi @mschrothglanz ! I will get back to you on task 4, I see what you mean now. I will also work on task 5, shouldn't be too complicated. 
I wanted to quickly ask you about the pixilation. I can totally separate it into some files doing one thing and other doing something else. So our whale and dolphin with have one type of graph and the others will have the pixilated one. However, I will not be able to know what to do for the user inputted files. Is that okay? What should be the default?

**Comment by mschrothcp** [comment]
Hmmm, that is a good question. Why don't you make the default for the uploaded ones whatever works best for the "nature" files as those will be the ones that are most likely to be uploaded.

Thanks for everything @michalg04 !

**Comment by mschrothcp** [comment]
Also, @michalg04 are you free tomorrow morning (Tuesday 7/28) say around 9 or 10 am? We should try to schedule a time to take the photos for the Frost submission.

**Comment by michalg04** [comment]
@mschrothglanz yes I am free then! 9:30?

**Comment by mschrothcp** [comment]
That works! Talk to you then!

**Comment by michalg04** [comment]
@mschrothglanz I got the beluga to load on my computer! I didn't change anything in the code just open and closed R a few times and it loaded... can't really explain why that happens since I'm not seeing any errors in the code show up, maybe @hglanz would know. 
<img width="659" alt="Screen Shot 2020-07-28 at 10 23 22 AM" src="https://user-images.githubusercontent.com/35315239/88699398-21ef9580-d0bc-11ea-8381-795309b07be0.png">

**Comment by michalg04** [comment]
@mschrothglanz I believe that I have done everything we've talked about! 
Except for figuring out why sometimes files don't load at all :) I think that the beluga and the file you sent me both looks really nice in either tabs, so I'm actually happy with the results! 
Sampling rate is being calculated by taking the original wave sample rate and dividing it by integers 1-20, creating 20 options. Segmentation works now on the file you emailed me and on others. I added the hover button, and a help button for the min segments. Pixilation also works now depending on the kind of file you have within the built in ones, and is smooth as a default. I also remembered that we can actually use the tiles and smooth at the same time, but I think we decided against that because it created some background pixilation. Let me know if you want to revisit that at some point. 
Good luck with your move!!

**Comment by mschrothcp** [comment]
Hey @michalg04 , we have moved into our new place which means I am ready to dedicate all my time to our fun project. It seems like the app is experiencing some issues with the audio playback. After last time, we realized that in order to look at a new  file that we wanted to upload we first had to look at one of the preloaded files. However, once I choose to upload a new file, it still retains the old audio. You can see the discrepancy in the picture below. I looked at the triangle file first and then tried the beluga, but the triangle audio is still there. I think the three of us need to chat some before I send this off to my collaborator. I don't want her to complain about the small issues instead of focusing on the big picture and I have a feeling this will be part of the things she focuses on. So, @hglanz and @michalg04 , I propose we try a time on either Wed, Thurs, or Fri of this week for a zoom chat. Let me know what days and times work for you guys.

![image](https://user-images.githubusercontent.com/52642916/89256975-2515e480-d5da-11ea-9791-9e34dabbebec.png)

**Comment by michalg04** [comment]
@mschrothglanz I'm free Wed after 6:30, or Friday after 6. Is that too late?

**Comment by mschrothcp** [comment]
Wed at 6:30 works for me (and @hglanz I believe). I have put it in the calendar! Chat with you then.

**Comment by michalg04** [comment]
<img width="820" alt="Screen Shot 2020-08-04 at 9 22 57 PM" src="https://user-images.githubusercontent.com/35315239/89371446-4210ed00-d698-11ea-8684-f3422f50f838.png">
I think I fixed it by the way!

**Comment by michalg04** [comment]
@mschrothglanz @hglanz made some changes to the app since our last talk! Changed the location of the play button, fixed the red lines to move once the spectrum duration is specified, and removed min/max freq/time. What do you guys think about removing the checks and just having the side inputs? I think having the extra checkbox is an extra if statement that slows down loading too. Let me know!

**Comment by mschrothcp** [comment]
Hey @michalg04 ! Great job on everything so far! First, thank you for changing the spectrum bars, they work great now. Second, can you make the play button only as long as the two left graphs (and not the whole window length) so that it matches with the timing on the spectrogram and oscillogram? Third, let's try removing the checks on the side panel and see how much we get from that. Great work!

**Comment by michalg04** [comment]
Hey @mschrothglanz! I made the changes above. I think it's working much better without the checks. See you tonight!

**Comment by michalg04** [comment]
@mschrothglanz @hglanz I haven't been able to figure out what caused the dolphin file to slow down so much, but I did make some changes that seem to have made it run faster. Let me know if it works better on your end. I tried to mess around with the question marks buttons, but I think the display depends on the screen size you have and I'm having a hard time gauging what it looks like on average. Could you guys let me know if you see a difference between @hglanz computer and @mschrothglanz computer? Thank you!

**Comment by mschrothcp** [comment]
Hey @michalg04 ! Apologies, again, for the delayed response. I'm trying the dolphin file now and it seems to be faster than before. It still took a little to load, but it was MUCH faster than the last time we talked!!! @hglanz hasn't tried it on his computer yet, but I'm hoping he will soon. I think the app is in a really good condition to send to our collaborator and so I will get that out by the end of the week. If you can continue to work on packaging it up with a set of instructions as @hglanz mentioned in our last email, that would be great!! I will keep you posted! Thanks so much!!

**Comment by michalg04** [comment]
Hey @mschrothglanz ! I noticed that there was a problem with segmentation. I just fixed it but you might have to let Ann know if you already updated her. Sorry about that!

**Comment by mschrothcp** [comment]
@michalg04 , thanks for letting me know.

**Comment by michalg04** [comment]
@mschrothglanz @hglanz sorry I haven't gotten around to writing the instructions! My house is very close to the fires so we have been staying at a family friends house for a while and things are just getting back to normal. Are there any specific things you'd like me to include with the instructions? I was just going to do a standard code "read me". Thanks!

**Comment by mschrothcp** [comment]
@michalg04 please please please don't apologize or worry. @hglanz and I have been busy working on prepping for Fall and our collaborator Ann hasn't gotten back to us yet.  Since we don't really have big things to work on for the app other than creating the instructions, there is absolutely no time pressure here. It is, at this point, however long you are willing to keep working with us. We aren't worried about the Frost timeline whatsoever. Please just be safe and keep us updated. I hope your home is okay and all of your family is okay. I'm so sorry that you have to be dealing with this.

**Comment by michalg04** [comment]
@mschrothglanz @hglanz thank you for your patience, I appreciate it! I fixed the problem I was having earlier with github, so all the recent code is now up on this repo. I also added a txt file with instructions and updated the "about" page on the app. My instructions are pretty similar to the about page, just a few more technical detail about running the app locally. Let me know what you think and if Ann got back to you! I was also wondering if either of you were still interested in publishing the app and writing about it? 
Thank you and good luck with the start of the quarter!

**Comment by mschrothcp** [comment]
@michalg04 , it is really good to hear from you. How is everything going? Are you back at your house? Let us know how things are for you...hopefully well!
So, good/bad news....Ann did get back to me but only to tell me how busy she currently is and how she needs some time to really vet our app. I'm excited for her report back, it will be very helpful. Now, we are definitely interested in tying to publish the work you have done, but I'm hoping that Ann can help provide some valuable feedback for us. We are hoping that you too are interested in publishing, but completely understand if your plate is getting too full. For the time being, while Ann is reviewing our app, there isn't much work to be done.

**Comment by michalg04** [comment]
@mschrothglanz yes everything is back to normal now, thanks for asking! (minus the air quality of course).  How are you guys? 
I was wondering if you and @hglanz would want to meet and talk about publishing? I don't remember if I told you guys or not but I ended up leaving my job so I do have some extra time on my hands and don't mind spending some of it writing even before Ann gets back to us just so we can get ahead on it.  Let me know what you think. Thank you!

**Comment by mschrothcp** [comment]
Hey @michalg04 ! So first, so very sorry it has taken us so long to get back to you, this first week was madness! I don't remember you telling us about your job, but I'm glad that you made the best choice for yourself given those un-ideal circumstances. Given that, I think we can certainly set up a time to chat about a publication. Unfortunately Ann hasn't gotten back to me, but perhaps you, @hglanz , and I can talk about the bare bones and what we think could work so that you could possibly get started. Are there good times in the week that work for you to chat?

**Comment by michalg04** [comment]
Hi @mschrothglanz! No problem and glad you survived the first week! I am pretty free this week so I should be able to make any time work! Let me know when you and @hglanz are free. Thank you!

**Comment by mschrothcp** [comment]
Sweet! Would this Friday afternoon work sometime, say around 2?

**Comment by michalg04** [comment]
@mschrothglanz that works, thanks! See you then :)
