### ISSUE TITLE
Segmentation Tab

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#7]
Started working on segmentation tab. Using autodetec from warbleR. 
(this is to document what I'm working on) 
@hglanz

**Comment by michalg04** [comment]
I'm playing around with different segmentation methods and I found one that does a good job for our files, and can actually segment the whale file (which the first one couldn't). It also produces data frames with time and amplitude segments. Does something like this look good or is it not in the right direction?  @hglanz @mschrothglanz 

<img width="821" alt="Screen Shot 2019-07-22 at 4 51 33 PM" src="https://user-images.githubusercontent.com/35315239/61672573-febc2a00-aca0-11e9-8723-ca1d1fb0c263.png">
<img width="806" alt="Screen Shot 2019-07-22 at 4 51 17 PM" src="https://user-images.githubusercontent.com/35315239/61672576-ffed5700-aca0-11e9-9ea2-6fd99dfe3a5e.png">

**Comment by hglanz** [comment]
@michalg04 I'm excited about what you've said, but could you explain how to read these plots? The red stars, etc.?

**Comment by michalg04** [comment]
@hglanz from what I've read about the function, the blue segments are syllables and the red stars are bursts. Segment() defines syllables as continuous segments with amplitude above a certain threshold, and bursts as local maxima in amplitude that are high enough both relative to the global max and relative to local min.

**Comment by hglanz** [comment]
So, am I to understand that this method is only looking at the amplitude vs. time content of the recording?

I like these pictures, it seems to be doing well, and I am happy to hear it does well on other files. @mschrothglanz is telling me that it is perfectly fine for the segmentation method to only look at amplitude over time. So, if you like this method and it is relatively easy to produce the graphs and results...then let's go with it!

Thanks!

**Comment by michalg04** [comment]
@hglanz yes that's exactly what it is doing. Glad to hear that!
