### ISSUE TITLE
Meeting 07/19

### ISSUE THREAD

**Issue by michalg04** [hglanz/AcousticsApp-Summer2019#9]
@hglanz @mschrothglanz would it be possible to move our Friday meeting this week to Monday? My mom's birthday is on Thursday so she was asking if I could stay for the weekend. Totally understand if not since it's been a while since we met. Let me know what works best for you!

**Comment by mschrothcp** [comment]
@michalg04 I'm sorry we didn't get back to you sooner on this issue. Unfortunately we won't be in town next week, however I believe that perhaps we could move our meeting earlier this week to compensate for our absence. @hglanz what do you think?

**Comment by hglanz** [comment]
Yes, sorry for the delayed response. I need to contact the person who was going to record us to see if they're open to rescheduling. You should feel free to plan on being away for the weekend. That will be fine.

**Comment by michalg04** [comment]
I think Friday as planned would be better for me than earlier in the week, since I could go home before and spend a few days there then. Will you be gone all of next week?

**Comment by hglanz** [comment]
Unfortunately yes. We are leaving Monday and will be gone until 8/8. So we are keeping our regularly scheduled Friday meeting at 1pm?

**Comment by hglanz** [comment]
@michalg04 ? Sorry, I just want to clarify so I can finalize with the CSM media person.

**Comment by michalg04** [comment]
Yes sorry! Let's do friday. Would it be possible to do our meeting at around 3 or 4? If not, 1pm is great. I was just looking at train times and they are either early in the morning or late afternoon. @hglanz

**Comment by hglanz** [comment]
@michalg04 Friday at 3 or 4 is fine. Just let us know which is best for you. Thanks!

**Comment by michalg04** [comment]
@hglanz 4pm would be best! Thank you so much!

**Comment by hglanz** [comment]
@michalg04 No problem. Thanks for the quick communication! We'll be meeting in 180-372 because we'll be recorded. We'll see you there.
